name: where-is-my-pal-dev

secrets:
  app_secrets:
    file: ./secrets.env

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whereismypal_dev
    container_name: wimp-dev-container
    secrets:
      - app_secrets
    ports:
      - "8000:8000"
    volumes:
      # - ./static:/app/staticfiles
      # - ./db.sqlite3:/db.sqlite3
      - ./prod:/app/prod
      - ./prod/media:/app/staticfiles/pets