name: where-is-my-pal-dev

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: whereismypal_dev
    container_name: wimp-dev-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/db.sqlite3