# Generated by Django 6.0.2 on 2026-02-27 22:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimp_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrPet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_to', models.CharField(max_length=255, verbose_name='Redirects to')),
            ],
        ),
    ]
