# Generated by Django 6.0.2 on 2026-03-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimp_base', '0002_qrpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(default='pets/default.jpg', upload_to='pets/'),
        ),
    ]
