# Generated by Django 6.0.2 on 2026-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimp_base', '0003_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
