# Generated by Django 6.0.2 on 2026-03-06 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimp_base', '0005_sitesettings_alter_pet_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpet',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Pet to generate QR code for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='wimp_base.pet'),
        ),
        migrations.AddField(
            model_name='qrpet',
            name='qr_image',
            field=models.ImageField(blank=True, help_text='Generated QR code image', upload_to='qr_codes/', verbose_name='QR Code Image'),
        ),
        migrations.AlterField(
            model_name='qrpet',
            name='redirect_to',
            field=models.CharField(blank=True, help_text='Auto-generated URL based on pet ID', max_length=255, verbose_name='Redirects to'),
        ),
    ]
