# Generated by Django 6.0.2 on 2026-03-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimp_base', '0006_qrpet_pet_qrpet_qr_image_alter_qrpet_redirect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='instagram',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
